CREATE ROLE airfi;
CREATE DATABASE airflow;
GRANT ALL PRIVILEGES on database airflow to airfi;
ALTER ROLE airfi SUPERUSER;
ALTER ROLE airfi CREATEDB;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to airfi;
